import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })

import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
const  Navbar = dynamic(() => import('../components/Navbar'), { ssr: false })
const Todos = dynamic(() => import('../components/Todos'), {ssr: false})
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-700 h-screen'>
        <Navbar />
        <Todos />
      </main>
    </>
  )
}
